add_executable(01-intro-fundamentals-of-array 01-intro-fundamentals-of-array.cpp)
add_executable(02-types-of-arrays 02-types-of-arrays.cpp)
add_executable(03-array-memory-model 03-array-memory-model.cpp)
add_executable(04-array-operations 04-array-operations.cpp)
add_executable(05-arrays-and-functions 05-arrays-and-functions.cpp)
add_executable(06-character-arrays 06-character-arrays.cpp)
add_executable(07-c-style-arrays 07-c-style-arrays.cpp)
add_executable(08-std-array 08-std-array.cpp)
add_executable(09-comparision-of-array-types 09-comparision-of-array-types.cpp)
add_executable(10-intro-fundamentals-of-strings 10-intro-fundamentals-of-strings.cpp)
add_executable(11-c-style-strings 11-c-style-strings.cpp)
add_executable(12-c-style-library 12-c-style-library.cpp)
add_executable(13-std-string 13-std-string.cpp)
add_executable(14-string-input-and-output 14-string-input-and-output.cpp)
add_executable(15-string-iteration 15-string-iteration.cpp)
add_executable(16-std-string_view 16-std-string_view.cpp)
add_executable(17-raw-string-literals 17-raw-string-literals.cpp)
add_executable(18-unicode-strings 18-unicode-strings.cpp)
add_executable(19-array-and-string-algorithms 19-array-and-string-algorithms.cpp)
add_executable(20-arrays-vs-strings 20-arrays-vs-strings.cpp)
add_executable(21-best-practices-arrays-strings 21-best-practices-arrays-strings.cpp)
add_executable(22-common-mistakes-arrays-strings 22-common-mistakes-arrays-strings.cpp)
add_executable(23-performance-considerations-arrays-strings 23-performance-considerations-arrays-strings.cpp)