add_executable(01-introduction-pamm 01-introduction-pamm.cpp)
add_executable(02-memory-organisation 02-memory-organisation.cpp)
add_executable(03-memory-addresses 03-memory-addresses.cpp)
add_executable(04-variables-and-memory 04-variables-and-memory.cpp)
add_executable(05-basics-of-pointers 05-basics-of-pointers.cpp)
add_executable(06-address-of-operator 06-address-of-operator.cpp)
add_executable(07-dereference-pointer 07-dereference-pointer.cpp)
add_executable(08-pointer-types 08-pointer-types.cpp)
add_executable(09-pointer-initialisation 09-pointer-initialisation.cpp)
add_executable(10-pointer-arithmetic 10-pointer-arithmetic.cpp)
add_executable(11-arrays-and-pointers 11-arrays-and-pointers.cpp)
add_executable(12-pointer-to-pointer 12-pointer-to-pointer.cpp)
add_executable(13-dynamic-memory-allocation 13-dynamic-memory-allocation.cpp)
add_executable(14-new-delete-operators 14-new-delete-operators.cpp)
add_executable(15-memory-leaks 15-memory-leaks.cpp)
add_executable(16-dangling-pointers 16-dangling-pointers.cpp)
add_executable(17-wild-null-void-pointers 17-wild-null-void-pointers.cpp)
add_executable(18-const-and-pointers 18-const-and-pointers.cpp)
add_executable(19-references-and-pointers 19-references-and-pointers.cpp)
add_executable(20-dynamic-arrays 20-dynamic-arrays.cpp)
add_executable(21-pointers-and-functions 21-pointers-and-functions.cpp)
add_executable(22-function-pointers 22-function-pointers.cpp)
add_executable(23-pointers-and-objects 23-pointers-and-objects.cpp)
add_executable(24-pointer-to-members 24-pointer-to-members.cpp)
add_executable(25-memory-manipulation 25-memory-manipulation.cpp)
add_executable(26-alignment-and-padding 26-alignment-and-padding.cpp)
add_executable(27-dynamic-memory-pitfalls 27-dynamic-memory-pitfalls.cpp)
add_executable(28-ownership 28-ownership.cpp)
add_executable(29-RAII-relationship 29-RAII-relationship.cpp)
add_executable(30-best-practices-pamm 30-best-practices-pamm.cpp)
add_executable(31-common-mistakes-pamm 31-common-mistakes-pamm.cpp)
add_executable(32-performance-considerations-pamm 32-performance-considerations-pamm.cpp)