add_executable(01-intro-namespace-translation-units 01-intro-namespace-translation-units.cpp)
add_executable(02-namespace-fundamentals-and-scope-resolution-operator 02-namespace-fundamentals-and-scope-resolution-operator.cpp)
add_executable(03-using-declarations-and-directives 03-using-declarations-and-directives.cpp)
add_executable(04-namespace-aliases 04-namespace-aliases.cpp)
add_executable(05-namespace-lookup 05-namespace-lookup.cpp)
add_executable(06-standard-namespace 06-standard-namespace.cpp)
add_executable(07-translation-unit 07-translation-unit.cpp)
add_executable(08-source-files-header-files 08-source-files-header-files.cpp)
add_executable(09-header-inclusion 09-header-inclusion.cpp)
add_executable(10-include-guards 10-include-guards.cpp)
add_executable(11-pragma-once 11-pragma-once.cpp)
add_executable(12-compilation-process 12-compilation-process.cpp)
add_executable(13-linkage 13-linkage.cpp)
add_executable(14-storage-duration-vs-linkage 14-storage-duration-vs-linkage.cpp)
add_executable(15-one-definition-rule 15-one-definition-rule.cpp)
add_executable(16-forward-declarations 16-forward-declarations.cpp)
add_executable(17-circular-dependencies 17-circular-dependencies.cpp)
add_executable(18-interface-vs-implementation 18-interface-vs-implementation.cpp)
add_executable(19-symbol-visibility 19-symbol-visibility.cpp)
add_executable(20-static-and-extern 20-static-and-extern.cpp)
add_executable(21-organising-large-projects 21-organising-large-projects.cpp)
add_executable(22-best-practices 22-best-practices.cpp)
add_executable(23-common-mistakes 23-common-mistakes.cpp)
add_executable(24-performance-considerations-natu 24-performance-considerations-natu.cpp)