# Define the executable binary target name and its corresponding source code file
add_executable(hello-world hello-world.cpp)

add_executable(01-structure-of-c++ 01-structure-of-c++.cpp)
add_executable(02-tokens 02-tokens.cpp)
add_executable(03-character-set-and-escape-sequences 03-character-set-and-escape-sequences.cpp)
add_executable(04-variables-and-datatypes 04-variables-and-datatypes.cpp)
add_executable(05-integer-and-floating-point-types 05-integer-and-floating-point-types.cpp)
add_executable(06-boolean-type-and-character-type 06-boolean-type-and-character-type.cpp)
add_executable(07-constants 07-constants.cpp)
add_executable(08-literals 08-literals.cpp)
add_executable(09-operators 09-operators.cpp)
add_executable(10-expressions 10-expressions.cpp)
add_executable(11-operator-precedence-and-associativity 11-operator-precedence-and-associativity.cpp)
add_executable(12-type-conversion 12-type-conversion.cpp)
add_executable(13-storage-duration 13-storage-duration.cpp)
add_executable(14-scope 14-scope.cpp)
add_executable(15-storage-class-specifiers 15-storage-class-specifiers.cpp)
add_executable(16-type-deduction 16-type-deduction.cpp)
add_executable(17-enumeration 17-enumeration.cpp)
add_executable(18-alias-declaration 18-alias-declaration.cpp)
add_executable(19-input-and-output 19-input-and-output.cpp)
add_executable(20-basic-stl 20-basic-stl.cpp)
add_executable(21-basic-programming-termination 21-basic-programming-termination.cpp)
add_executable(22-coding-style-basics 22-coding-style-basics.cpp)