add_executable(01-introduction-RAII 01-introduction-RAII.cpp)
add_executable(02-understanding-resources 02-understanding-resources.cpp)
add_executable(03-object-lifetime 03-object-lifetime.cpp)
add_executable(04-constructors 04-constructors.cpp)
add_executable(05-destructors 05-destructors.cpp)
add_executable(06-constructor-destructor-relationship 06-constructor-destructor-relationship.cpp)
add_executable(07-core-principles-of-RAII 07-core-principles-of-RAII.cpp)
add_executable(08-scope-based-resource-management 08-scope-based-resource-management.cpp)
add_executable(09-resource-ownership-models 09-resource-ownership-models.cpp)
add_executable(10-memory-management-with-RAII 10-memory-management-with-RAII.cpp)
add_executable(11-file-and-lock-management 11-file-and-lock-management.cpp)
add_executable(12-managing-multiple-resources 12-managing-multiple-resources.cpp)
add_executable(13-RAII-exception-safety 13-RAII-exception-safety.cpp)
add_executable(14-destructor-behaviour-during-expectations 14-destructor-behaviour-during-expectations.cpp)
add_executable(15-copying-RAII-objects 15-copying-RAII-objects.cpp)
add_executable(16-non-copyable-RAII-objects 16-non-copyable-RAII-objects.cpp)
add_executable(17-move-inly-RAII-objects 17-move-inly-RAII-objects.cpp)
add_executable(18-RAII-in-standard-library 18-RAII-in-standard-library.cpp)
add_executable(19-designing-RAII-classes 19-designing-RAII-classes.cpp)
add_executable(20-resource-wrappers 20-resource-wrappers.cpp)
add_executable(21-lifetime-management 21-lifetime-management.cpp)
add_executable(22-deterministic-destruction 22-deterministic-destruction.cpp)
add_executable(23-RAII-design-principles 23-RAII-design-principles.cpp)
add_executable(24-common-RAII-patterns 24-common-RAII-patterns.cpp)
add_executable(25-best-practices-RAII 25-best-practices-RAII.cpp)
add_executable(26-common-mistakes-RAII 26-common-mistakes-RAII.cpp)
add_executable(27-performance-considerations-RAII 27-performance-considerations-RAII.cpp)
add_executable(28-relationsip-with-other-topics 28-relationsip-with-other-topics.cpp)