add_executable(01-introduction-template 01-introduction-template.cpp)
add_executable(02-function-templates-template-argument-deduction 02-function-templates-template-argument-deduction.cpp)
add_executable(03-function-template-overloading 03-function-template-overloading.cpp)
add_executable(04-explicit-template-arguments 04-explicit-template-arguments.cpp)
add_executable(05-class-templates 05-class-templates.cpp)
add_executable(06-template-class-initialisation 06-template-class-initialisation.cpp)
add_executable(07-non-type-template-parameters 07-non-type-template-parameters.cpp)
add_executable(08-explicit-specialisation 08-explicit-specialisation.cpp)
add_executable(09-partial-specialisation 09-partial-specialisation.cpp)
add_executable(10-full-vs-partial-specialisation 10-full-vs-partial-specialisation.cpp)
add_executable(11-template-parameter-types 11-template-parameter-types.cpp)
add_executable(12-default-template-arguments 12-default-template-arguments.cpp)
add_executable(13-variadic-templates 13-variadic-templates.cpp)
add_executable(14-fold-expressions 14-fold-expressions.cpp)
add_executable(15-type-deduction-rules 15-type-deduction-rules.cpp)
add_executable(16-reference-collapsing 16-reference-collapsing.cpp)
add_executable(17-template-instantiation-model 17-template-instantiation-model.cpp)
add_executable(18-one-definition-rule-and-templates 18-one-definition-rule-and-templates.cpp)
add_executable(19-alias-templates 19-alias-templates.cpp)
add_executable(20-variable-templates 20-variable-templates.cpp)
add_executable(21-member-templates 21-member-templates.cpp)
add_executable(22-template-friends 22-template-friends.cpp)
add_executable(23-template-meta-programming 23-template-meta-programming.cpp)
add_executable(24-recursive-template 24-recursive-template.cpp)
add_executable(25-type-traits 25-type-traits.cpp)
add_executable(26-SFINAE 26-SFINAE.cpp)
add_executable(27-std-enable_if 27-std-enable_if.cpp)
add_executable(28-concepts 28-concepts.cpp)
add_executable(29-requires-expressions 29-requires-expressions.cpp)
add_executable(30-generic-programming-principles 30-generic-programming-principles.cpp)
add_executable(31-template-design-guidelines 31-template-design-guidelines.cpp)
add_executable(32-templates-in-standard-library 32-templates-in-standard-library.cpp)
add_executable(33-best-common-and-performance-considerations-template 33-best-common-and-performance-considerations-template.cpp)