add_executable(01-introduction-oop 01-introduction-oop.cpp)
add_executable(02-classes-and-objects 02-classes-and-objects.cpp)
add_executable(03-data-members 03-data-members.cpp)
add_executable(04-member-functions 04-member-functions.cpp)
add_executable(05-this-pointer 05-this-pointer.cpp)
add_executable(06-constructors-destructors 06-constructors-destructors.cpp)
add_executable(07-object-construction-destruction 07-object-construction-destruction.cpp)
add_executable(08-encapsulation 08-encapsulation.cpp)
add_executable(09-access-specifiers 09-access-specifiers.cpp)
add_executable(10-abstraction 10-abstraction.cpp)
add_executable(11-static-data-members-functions 11-static-data-members-functions.cpp)
add_executable(12-friends-functions-classes 12-friends-functions-classes.cpp)
add_executable(13-overloading 13-overloading.cpp)
add_executable(14-copy-and-move-semantics 14-copy-and-move-semantics.cpp)
add_executable(15-rule-of-three 15-rule-of-three.cpp)
add_executable(16-rule-of-five 16-rule-of-five.cpp)
add_executable(17-rule-of-zero 17-rule-of-zero.cpp)
add_executable(18-inheritance 18-inheritance.cpp)
add_executable(19-polymorphism 19-polymorphism.cpp)
add_executable(20-object-and-relationships 20-object-and-relationships.cpp)
add_executable(21-advanced-features 21-advanced-features.cpp)
add_executable(22-best-performance-and-common-mistakes 22-best-performance-and-common-mistakes.cpp)