add_executable(01-introduction-eh 01-introduction-eh.cpp)
add_executable(02-types-of-program-errors 02-types-of-program-errors.cpp)
add_executable(03-exception-model 03-exception-model.cpp)
add_executable(04-throw-statement 04-throw-statement.cpp)
add_executable(05-exception-objects 05-exception-objects.cpp)
add_executable(06-try-catch-blocks 06-try-catch-blocks.cpp)
add_executable(07-exception-propagation-rethrowing-exceptions 07-exception-propagation-rethrowing-exceptions.cpp)
add_executable(08-stack-unwinding 08-stack-unwinding.cpp)
add_executable(09-RAII-and-exceptions 09-RAII-and-exceptions.cpp)
add_executable(10-standard-exception-hierarchy 10-standard-exception-hierarchy.cpp)
add_executable(11-common-standard-exceptions 11-common-standard-exceptions.cpp)
add_executable(12-exception-information 12-exception-information.cpp)
add_executable(13-creating-custom-exceptions 13-creating-custom-exceptions.cpp)
add_executable(14-exception-class-design 14-exception-class-design.cpp)
add_executable(15-noexcept 15-noexcept.cpp)
add_executable(16-legacy-excepton-specifications 16-legacy-excepton-specifications.cpp)
add_executable(17-exception-safety-guarantees 17-exception-safety-guarantees.cpp)
add_executable(18-writing-exception-safecode 18-writing-exception-safecode.cpp)
add_executable(19-constructors-destructors-exceptions 19-constructors-destructors-exceptions.cpp)
add_executable(20-exception-acrossfunction-boundaries 20-exception-acrossfunction-boundaries.cpp)
add_executable(21-exception-and-return-values 21-exception-and-return-values.cpp)
add_executable(22-polymorphic-exceptions 22-polymorphic-exceptions.cpp)
add_executable(23-modern-exception-handling 23-modern-exception-handling.cpp)
add_executable(24-exceptions-in-multithreading 24-exceptions-in-multithreading.cpp)
add_executable(25-exception-handling-performance 25-exception-handling-performance.cpp)
add_executable(26-best-common-and-debugging-exceptions 26-best-common-and-debugging-exceptions.cpp)